org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.234
neo_version_range=[21.1.234,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

ponder_version=1.0.87+mc1.21.1
flywheel_version=1.0.6

mod_id=arc_quest
mod_name=Arc Quest
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=org.arcadia
mod_authors=Arcad1a, P1nero
mod_description=Arc Quest by Arcad1a, Credits by P1nero's dialogue lib and Tcr Core

systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7890
