package org.arcadia.arc_quest.client.hud.quest.editor;

public enum QuestEditorMode {
    IDLE,
    PLACE_PHASE,
    DELETE_PHASE_SELECT,
    CONNECT_GOTO,
    DRAG_PHASE,
    CONNECTION_SELECTED,
    PHASE_EDIT_MODAL,
    IMPORT_MODAL,
    CREATE_QUEST_MODAL,
    DELETE_CONFIRM_MODAL,
    COLLECTION_CATEGORY_SELECTED,
    COLLECTION_ENTRY_SELECTED,
    PLACE_COLLECTION_CATEGORY,
    PLACE_COLLECTION_ENTRY,
    DELETE_COLLECTION_OBJECT_SELECT,
    COLLECTION_OBJECT_EDIT_MODAL
}
