package org.arcadia.arc_quest.client.hud.guide;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.minecraft.util.FormattedCharSequence;
import org.arcadia.arc_quest.client.hud.HudAnimUtil;

import java.util.List;

final class GuideContentPanel {
    private final GuideListScreen screen;
    GuideContentPanel(GuideListScreen screen){this.screen=screen;}

    void render(GuiGraphics g,int mouseX,int mouseY,float partialTick,int alpha){int[] r=screen.contentRect();HudAnimUtil.drawFrame(g,r[0],r[1],r[2],r[3],withAlpha(0x000000,(int)(alpha*.4f)),withAlpha(screen.getThemeColor(),(int)(alpha*.55f)));if(!screen.hasAnyVisibleGuide()){GuideNavigationControls.drawScaledText(screen,g,r[0]+16,r[1]+18,.92f,"Guide Terminal",withAlpha(GuideScreen.TEXT,alpha));GuideNavigationControls.drawScaledText(screen,g,r[0]+16,r[1]+42,.78f,Component.translatable("gui.arc_quest.guide_list.no_guides").getString(),withAlpha(GuideScreen.SUB,alpha));return;}GuideListScreen.GuidePageView view=screen.currentPageView();if(view==null)return;GuideNavigationControls.drawScaledText(screen,g,r[0]+16,r[1]+12,1.04f,view.guide().getTitle().getString(),withAlpha(GuideScreen.TEXT,alpha));g.drawString(Minecraft.getInstance().font,"PAGE "+(view.pageIndex()+1)+" / "+view.guide().getPageCount(),r[0]+r[2]-84,r[1]+14,withAlpha(GuideScreen.SUB,alpha),false);int mediaX=r[0]+16,mediaY=r[1]+34,mediaW=r[2]-32,mediaH=128;GuideMediaRenderer.drawMedia(screen,g,mediaX,mediaY,mediaW,mediaH,view.page().getMedia(),screen.ponderPanel(),mouseX,mouseY,partialTick,alpha,GuideScreen.SEC,GuideScreen.MUTED,GuideScreen.SUB,screen.getThemeColor());int[] d=descriptionRect();int descX=d[0],descY=d[1],descW=d[2],descH=d[3];List<FormattedCharSequence> lines=screen.descriptionLines(descW);int contentH=lines.size()*GuideScreenLayout.TEXT_LINE_H,max=Math.max(0,contentH-descH);screen.setDescTargetScroll(clamp(screen.getDescTargetScroll(),0d,max));screen.setDescScroll(clamp(screen.getDescScroll(),0d,max));g.enableScissor(descX-2,descY-2,descX+descW+2,descY+descH+2);int sy=descY-(int)Math.round(screen.getDescScroll());for(int i=0;i<lines.size();i++)g.drawString(Minecraft.getInstance().font,lines.get(i),descX,sy+i*GuideScreenLayout.TEXT_LINE_H,withAlpha(GuideScreen.TEXT,alpha));g.disableScissor();if(max>0){int rx=descX+descW+4;g.fill(rx,descY,rx+2,descY+descH,withAlpha(0x22303A,alpha));int th=Math.max(12,(int)(descH*(descH/(float)contentH))),travel=Math.max(0,descH-th),ty=descY+(int)(travel*(screen.getDescScroll()/(double)max));g.fill(rx,ty,rx+2,ty+th,withAlpha(screen.getThemeColor(),alpha));}GuideNavigationControls.drawButton(screen,g,r[0]+16,r[1]+r[3]-22,GuideScreenLayout.CONTROL_W,GuideScreenLayout.CONTROL_H,"PREV",view.pageIndex()>0,hit(mouseX,mouseY,r[0]+16,r[1]+r[3]-22,GuideScreenLayout.CONTROL_W,GuideScreenLayout.CONTROL_H),screen.getThemeColor(),GuideScreen.TEXT,GuideScreen.DIS,alpha);GuideNavigationControls.drawButton(screen,g,r[0]+80,r[1]+r[3]-22,GuideScreenLayout.CONTROL_W,GuideScreenLayout.CONTROL_H,"NEXT",view.pageIndex()<view.guide().getPageCount()-1,hit(mouseX,mouseY,r[0]+80,r[1]+r[3]-22,GuideScreenLayout.CONTROL_W,GuideScreenLayout.CONTROL_H),screen.getThemeColor(),GuideScreen.TEXT,GuideScreen.DIS,alpha);} 
    boolean mouseClicked(double mouseX,double mouseY){int[] r=screen.contentRect();int y=r[1]+r[3]-22;if(hit(mouseX,mouseY,r[0]+16,y,GuideScreenLayout.CONTROL_W,GuideScreenLayout.CONTROL_H)){screen.prevPage();return true;}if(hit(mouseX,mouseY,r[0]+80,y,GuideScreenLayout.CONTROL_W,GuideScreenLayout.CONTROL_H)){screen.nextPage();return true;}return false;}
    boolean mouseScrolled(double mouseX,double mouseY,double delta){int[] d=descriptionRect();if(!hit(mouseX,mouseY,d[0],d[1],d[2]+8,d[3]))return false;screen.adjustDescScroll(-delta*18d);return true;}
    int[] descriptionRect(){int[] r=screen.contentRect();int mediaY=r[1]+34,mediaH=128,descY=mediaY+mediaH+16,descW=r[2]-54,descH=Math.max(42,r[3]-(descY-r[1])-32);return new int[]{r[0]+16,descY,descW,descH};}
    int descriptionLineCount(){return screen.descriptionLines(descriptionRect()[2]).size();}
    private boolean hit(double mx,double my,int x,int y,int w,int h){return mx>=x&&mx<=x+w&&my>=y&&my<=y+h;} private static double clamp(double v,double min,double max){return Math.max(min,Math.min(max,v));} private int withAlpha(int c,int a){return ((a&0xFF)<<24)|(c&0x00FFFFFF);} }
